### PR TITLE
Log errors when message sending fails

### PR DESCRIPTION
**Pull request by edoakes**

### CODE REVIEW

**Comment by codygibb** [comment]
What's the motivation behind this diff? I'm a little concerned that this is going to result in way too much logging in production, since agents close connections frequently.

Maybe debug level is more appropriate?

**Comment by evelynl94** [comment]
> What's the motivation behind this diff? I'm a little concerned that this is going to result in way too much logging in production, since agents close connections frequently.
> 
> Maybe debug level is more appropriate?

debug +1

**Comment by edoakes** [comment]
Sure, debug seems better. Alternatively could delineate between the closed connection and full buffer error messages.

It seems important to have more visibility into messages being dropped when the sending buffer is full aside from just the counter as it could have a large impact on performance. This would be particularly bad if the buffer is improperly sized and piece payload messages are frequently dropped, for example.

**Comment by codygibb** [comment]
Sending on a closed conn is very normal and I would rather we never log on this case.

Personally I feel that metrics are more useful than logs (especially given the scale of kraken clusters), however I don't see the harm in adding a debug log when dropping a message. But this should probably happen in `Conn.Send`.

**Comment by codygibb** [comment]
Closing due to inactivity.

**Pull request closed without merging**
